version: 2
jobs:
 build:
   docker:
     # Specify the version you desire here
     - image: circleci/php:8
     - image: circleci/mysql:5.7
       environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: yes
         MYSQL_USER: test
         MYSQL_ROOT_PASSWORD: ''
         MYSQL_DATABASE: laravel
   steps: 
     - checkout
     - run:
         name: Install PHP exts
         command: |
           sudo docker-php-ext-install zip
           sudo docker-php-ext-install pdo_mysql
           sudo apt update 
           sudo apt install default-mysql-client
     - run: sudo composer self-update

     # Download and cache dependencies
     - restore_cache:
         keys:
         - v1-dependencies-{{ checksum "composer.json" }}
         # fallback to using the latest cache if no exact match is found
         - v1-dependencies-

     - save_cache:
         paths:
           - ./vendor
         key: v1-dependencies-{{ checksum "composer.json" }}
     - run: 
          name: Run composer
          command: |
            composer update
            composer install
     - run: php artisan migrate:fresh --seed  --force
     - run: php artisan key:generate
     - run:
         name: Check convention PHP
         command: phpcs --standard=Framgia app
     - run:
         name: Check connection database
         command: framgia-ci test-connect 127.0.0.1 3306 60
     - run: php artisan migrate --seed --env=testing
     - run: ./vendor/bin/phpunit 
     - run: php artisan test --testsuite=Feature 'tests/Feature/Http/Controllers/PostControllerTest.php'
  
workflows:
 version: 2
 notify_deploy:
   jobs:
     - build